### ISSUE TITLE
Infinite Loop When Generating Test Class - Intellij

### ISSUE THREAD

**Issue by pmnymbl** [SquaretestLLC/Squaretest#18] opened 2019-12-16 14:35 UTC
1. I went to the class for which I wanted to generate a test class.
2. I selected Squaretest -> Generate Test.
3. I watched System Monitor and after using over 11 minutes of CPU time I forced quit Intellij.

This used to work without any issue.  I am currently on Intellij build #UI-193.5233.102.  I checked for updates and I have the latest version of Intellij IDEA and plugins installed.  This worked before I got the latest updates.

**Comment by pmnymbl** [comment] 2019-12-16 14:47
A co-worker just generated the code and is using Intellij build #IU-192.7142.36.

**Comment by nate-dev** [comment] 2019-12-16 15:46
Sorry for the inconvenience. This is the highest priority issue right now.

Could you please try the following?
Modify the template to change line 14 from:
`#set($maxRecursiveBeanInitDepth = 10)`
to
`#set($maxRecursiveBeanInitDepth = -1)`

To modify the template, go to **File** | **Settings** | **Squaretest**, scroll to the template in either the project or module settings, make the changes to the template text, and click **Apply**.

Then, try to generate the test class mentioned in your first post.

Also, are you seeing this issue for all classes you try to generate tests for or just one class?

**Comment by pmnymbl** [comment] 2019-12-17 14:01
I made that update.  I went back to make sure it took.  It is not generating new test methods for this class.  I can generate a new test class for a simple bean and a new test method for other service classes.

**Comment by pmnymbl** [comment] 2019-12-17 14:09
It does not seem to be working well with larger classes of around 200-300+ lines.  I created scrap class, moved a method there, and generated the test class.

**Comment by nate-dev** [comment] 2019-12-17 15:06
Thank you for the updates!

> It is not generating new test methods for this class.

Could you please try the following?
Open the test class and type **Alt** | **Insert** | **Generate Test Methods**.

Does Squaretest show a dialog with an error message?

**Comment by pmnymbl** [comment] 2019-12-17 16:01
I am using a mac os and not a windows os.

**Comment by nate-dev** [comment] 2019-12-17 16:04
Instead of:

> Open the test class and type Alt | Insert | Generate Test Methods.

Could you please try:
Open the test class and select **Squaretest | Generate Test Methods** from the tool bar?

**Comment by pmnymbl** [comment] 2019-12-17 16:06
Command + n worked.  No, there was no error box.  It does not respond and the cpu goes high.  I have to force quit the app.

**Comment by nate-dev** [comment] 2019-12-17 19:41
Thank you for helping to troubleshoot this! I believe I've determined the root cause.

I attached a build that I believe fixes the issue. Would you be willing to install it and try the following, again:  open the test class and select **Squaretest | Generate Test Methods** from the tool bar?

To install the build, go to:
**IntelliJ IDEA | Preferences | Plugins**.
Click the gear icon in the top, center part of the window and select **Install plugin from disk...**
Select the Squaretest.zip file containing the plugin. 
IntelliJ should ask you to restart the IDE to complete the install. Click the button to restart the IDE.

The build is here: [Squaretest.zip](https://github.com/SquaretestLLC/Squaretest/files/3974975/Squaretest.zip)

The build also writes additional logs that should identify the root cause of the issue if it is not fixed.

I apologize for the inconvenience. In the future, I will build debug logs into Squaretest and also provide a way to increase/decrease the log level from the settings.

**Comment by pmnymbl** [comment] 2019-12-18 15:12
That seems to have worked.  Thanks.

**Comment by nate-dev** [comment] 2020-02-17 16:03
Happy to help! I apologize for the delayed update on this. 

The fix for this issue was deployed in the 1.5.2 update released on 12/28/2019. The build I attached to this Github issue has version 1.5.1, so your IntelliJ IDEA install should update the plugin normally (show a notification that an update is available) if it hasn't already.

If you see this issue in the updated build, please let me know.

**Closed by nate-dev** 2020-02-17 16:03 UTC

**Comment by pmnymbl** [comment] 2020-02-17 16:22
Ok, thanks.
